services:
  polyis:
    build: .
    container_name: polyis-charliesi
    tty: true
    environment:
      - TERM=xterm-256color
      - POLYIS_DATA=/polyis-data
      - POLYIS_CACHE=/polyis-cache
    volumes:
      - .:/polyis
      # Change /data/chawutk/polyis-dataset to your local path
      - /data/charliesi/data/polyis-data:/polyis-data
      - /data/charliesi/data/polyis-cache:/polyis-cache
      # - /home/eecs/chanwutk/.ssh:/root/.ssh
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    network_mode: "host"