channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.13

  # darknet make dependency
  - nvidia/label/cuda-12.1.1::cuda-nvcc

  - pip
  - pip:  # Need to install torch and torchvision separately because of index url
    - --index-url https://download.pytorch.org/whl/cu124
    - torch
    - torchvision